import { Public_Sans } from "next/font/google";
import "./globals.css";
import Sidebar from "./Components/sidebar";

const publicSans = Public_Sans({
  variable: "--font-public-sans",
  subsets: ["latin"],
});

export const metadata = {
  title: "Finance App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${publicSans.variable} antialiased`}>
        <div className="relative lg:flex w-full h-screen">
          <Sidebar />
          <div className="flex-1">{children}</div>

        </div>

 
      </body>
    </html>
  );
}
